"""Composition root: the outermost edge, where the layers are joined."""

from composition.container import (
    SUPPORTED_DOMAIN_TOOL_PACKS,
    SUPPORTED_UPLOAD_SUFFIXES,
    available_providers,
    build_analyze_requirements,
    build_ask_knowledge,
    build_ask_service,
    build_chat_model,
    build_document_catalog,
    build_embedding_model,
    build_ingest_knowledge,
    build_invoke_tool,
    build_manage_uploaded_documents,
    build_orchestrate_software_delivery,
    build_prompt_repository,
    build_retrieve_knowledge,
    build_rewrite_and_retrieve_knowledge,
    build_tool_registry,
    build_vector_store,
    create_uploaded_document,
    delete_uploaded_document,
    ingest_uploaded_document,
    list_uploaded_documents,
    load_knowledge_documents,
    load_runtime_settings,
    probe_ollama,
    reindex_filter_metadata,
    replace_uploaded_document,
)
from composition.requirements_analysis import (
    RequirementsAnalysisFindingView,
    RequirementsAnalysisView,
    RequirementsAnalyzer,
    analysis_citations,
    requirements_analysis_enabled,
)
from composition.software_delivery_tools import (
    RiskFactorView,
    RiskScoreView,
    SoftwareDeliveryRunView,
    TestCaseView,
    TestCasesView,
    software_delivery_tools_enabled,
)
from composition.tool_runs import MAX_TOOL_CALL_SUMMARY_CHARS, ToolCallView
from composition.errors import (
    DocumentOperationError,
    DocumentUploadError,
    KnowledgeLoadError,
    PartialDocumentOperationError,
)
from infrastructure.config import Settings

__all__ = [
    "DocumentOperationError",
    "DocumentUploadError",
    "KnowledgeLoadError",
    "PartialDocumentOperationError",
    "MAX_TOOL_CALL_SUMMARY_CHARS",
    "SUPPORTED_DOMAIN_TOOL_PACKS",
    "SUPPORTED_UPLOAD_SUFFIXES",
    "Settings",
    "RequirementsAnalysisFindingView",
    "RequirementsAnalysisView",
    "RequirementsAnalyzer",
    "RiskFactorView",
    "RiskScoreView",
    "SoftwareDeliveryRunView",
    "TestCaseView",
    "TestCasesView",
    "ToolCallView",
    "analysis_citations",
    "requirements_analysis_enabled",
    "software_delivery_tools_enabled",
    "available_providers",
    "build_analyze_requirements",
    "build_ask_knowledge",
    "build_ask_service",
    "build_chat_model",
    "build_document_catalog",
    "build_embedding_model",
    "build_ingest_knowledge",
    "build_invoke_tool",
    "build_manage_uploaded_documents",
    "build_orchestrate_software_delivery",
    "build_prompt_repository",
    "build_retrieve_knowledge",
    "build_rewrite_and_retrieve_knowledge",
    "build_tool_registry",
    "build_vector_store",
    "create_uploaded_document",
    "delete_uploaded_document",
    "ingest_uploaded_document",
    "list_uploaded_documents",
    "load_knowledge_documents",
    "load_runtime_settings",
    "probe_ollama",
    "reindex_filter_metadata",
    "replace_uploaded_document",
]
