"""Behavior tests for the uploaded-file extraction adapter.

Every assertion goes through the public `extract_document` seam and the public
adapter errors. Real files under `tmp_path` and committed fixtures are the
behavior under test, so nothing here mocks `Path`, `pypdf`, or page extraction.
"""

import os
from pathlib import Path

import pytest
from pypdf import PdfWriter
from pypdf.errors import PyPdfError

from domain.errors import DomainValidationError
from domain.knowledge import SourceType
from infrastructure.documents.uploaded_files import (
    SUPPORTED_SUFFIXES,
    DocumentExtractionError,
    UnreadableDocumentError,
    UnsupportedDocumentError,
    extract_document,
)

# `date -u -r 1700000000` -> 2023-11-14T22:13:20+00:00. Pinned independently of
# the adapter so the expectation cannot drift with the production conversion.
_PINNED_MTIME = 1_700_000_000
_PINNED_MTIME_ISO = "2023-11-14T22:13:20+00:00"

# Committed fixture, regenerated by `test/fixtures/generate.py`.
_TWO_PAGE_PDF = Path(__file__).resolve().parents[2] / "fixtures" / "two_page.pdf"


def test_supported_suffixes_is_the_documented_set() -> None:
    assert SUPPORTED_SUFFIXES == frozenset({".txt", ".md", ".markdown", ".pdf"})


def test_txt_file_becomes_source_document(tmp_path: Path) -> None:
    path = tmp_path / "guide.txt"
    path.write_text("Kernector guidance body", encoding="utf-8")

    document = extract_document(path, source_id="upload:guide")

    assert document.content == "Kernector guidance body"
    assert document.source_id == "upload:guide"
    assert document.reference.source_type == SourceType.KNOWLEDGE_DOCUMENT


@pytest.mark.parametrize(
    "file_name,expected_format",
    [
        ("guide.txt", "txt"),
        ("guide.md", "markdown"),
        ("guide.markdown", "markdown"),
    ],
)
def test_text_suffix_maps_to_canonical_content_format(
    tmp_path: Path, file_name: str, expected_format: str
) -> None:
    path = tmp_path / file_name
    path.write_text("body", encoding="utf-8")

    document = extract_document(path, source_id="upload:guide")

    assert document.metadata.content_format == expected_format


@pytest.mark.parametrize(
    "file_name,expected_format",
    [
        ("GUIDE.TXT", "txt"),
        ("guide.Md", "markdown"),
        ("guide.MARKDOWN", "markdown"),
    ],
)
def test_suffix_matching_is_case_insensitive(
    tmp_path: Path, file_name: str, expected_format: str
) -> None:
    path = tmp_path / file_name
    path.write_text("body", encoding="utf-8")

    document = extract_document(path, source_id="upload:guide")

    assert document.metadata.content_format == expected_format


def test_markdown_markup_is_preserved_verbatim(tmp_path: Path) -> None:
    path = tmp_path / "guide.md"
    path.write_text("# Heading\n\nbody", encoding="utf-8")

    document = extract_document(path, source_id="upload:guide")

    assert document.content == "# Heading\n\nbody"


def test_basic_file_metadata_is_attached(tmp_path: Path) -> None:
    path = tmp_path / "guide.txt"
    path.write_text("Kernector guidance body", encoding="utf-8")  # 23 bytes
    os.utime(path, (_PINNED_MTIME, _PINNED_MTIME))

    document = extract_document(path, source_id="upload:guide")

    assert document.metadata.title == "guide"
    assert document.metadata.provider == "upload"
    assert document.metadata.extra == {
        "file_name": "guide.txt",
        "byte_size": "23",
        "modified_at": _PINNED_MTIME_ISO,
    }


@pytest.mark.parametrize(
    "file_name,expected_fragment",
    [
        ("report.docx", ".docx"),
        ("rows.csv", ".csv"),
        ("diagram.png", ".png"),
        ("README", "no suffix"),
    ],
)
def test_unsupported_file_type_is_rejected(
    tmp_path: Path, file_name: str, expected_fragment: str
) -> None:
    path = tmp_path / file_name
    path.write_text("body", encoding="utf-8")

    with pytest.raises(UnsupportedDocumentError) as error:
        extract_document(path, source_id="upload:thing")

    message = str(error.value)
    assert str(path) in message
    assert expected_fragment in message


def test_unsupported_file_type_is_rejected_before_filesystem_access(
    tmp_path: Path,
) -> None:
    """An unsupported type wins over a missing file, proving no I/O ran first."""
    with pytest.raises(UnsupportedDocumentError):
        extract_document(tmp_path / "absent.docx", source_id="upload:absent")


def test_text_based_pdf_becomes_source_document() -> None:
    """Pages join with a blank line, matching the fixture's two drawn lines."""
    document = extract_document(_TWO_PAGE_PDF, source_id="upload:two-page")

    assert document.content == "Page one body\n\nPage two body"
    assert document.metadata.content_format == "pdf"
    assert document.source_id == "upload:two-page"


def test_pdf_suffix_matching_is_case_insensitive(tmp_path: Path) -> None:
    upper = tmp_path / "GUIDE.PDF"
    upper.write_bytes(_TWO_PAGE_PDF.read_bytes())

    document = extract_document(upper, source_id="upload:guide")

    assert document.metadata.content_format == "pdf"


def test_pdf_page_count_is_attached() -> None:
    document = extract_document(_TWO_PAGE_PDF, source_id="upload:two-page")

    assert document.metadata.extra["page_count"] == "2"


@pytest.mark.parametrize("file_name", ["guide.txt", "guide.md"])
def test_page_count_is_absent_for_text_formats(
    tmp_path: Path, file_name: str
) -> None:
    path = tmp_path / file_name
    path.write_text("body", encoding="utf-8")

    document = extract_document(path, source_id="upload:guide")

    assert "page_count" not in document.metadata.extra


def test_adapter_errors_share_one_public_base() -> None:
    """Callers can catch the family, or distinguish the two failure kinds."""
    assert issubclass(UnsupportedDocumentError, DocumentExtractionError)
    assert issubclass(UnreadableDocumentError, DocumentExtractionError)


def test_missing_supported_file_is_unreadable(tmp_path: Path) -> None:
    with pytest.raises(UnreadableDocumentError) as error:
        extract_document(tmp_path / "absent.txt", source_id="upload:absent")

    assert isinstance(error.value.__cause__, OSError)


def test_directory_with_supported_suffix_is_unreadable(tmp_path: Path) -> None:
    directory = tmp_path / "notes.md"
    directory.mkdir()

    with pytest.raises(UnreadableDocumentError) as error:
        extract_document(directory, source_id="upload:notes")

    assert isinstance(error.value.__cause__, OSError)


def test_invalid_utf8_bytes_are_unreadable(tmp_path: Path) -> None:
    path = tmp_path / "guide.txt"
    path.write_bytes(b"\xff\xfe\x00 not utf-8")

    with pytest.raises(UnreadableDocumentError) as error:
        extract_document(path, source_id="upload:guide")

    assert isinstance(error.value.__cause__, UnicodeDecodeError)


@pytest.mark.parametrize(
    "file_name,content",
    [
        ("empty.txt", ""),
        ("blank.md", "   \n\t\n  "),
    ],
)
def test_file_without_extractable_text_is_unreadable(
    tmp_path: Path, file_name: str, content: str
) -> None:
    """A readable but textless file is an extraction failure, not a domain error."""
    path = tmp_path / file_name
    path.write_text(content, encoding="utf-8")

    with pytest.raises(UnreadableDocumentError, match="no extractable text"):
        extract_document(path, source_id="upload:blank")


@pytest.mark.parametrize("source_id", ["", "   ", "\n"])
def test_blank_source_id_is_a_caller_contract_violation(
    tmp_path: Path, source_id: str
) -> None:
    """Identity is validated by the domain, before any file is touched.

    The path is missing on purpose: an adapter error here would mean the
    filesystem was reached before the identity was checked.
    """
    with pytest.raises(DomainValidationError, match="source_id must be non-empty"):
        extract_document(tmp_path / "absent.txt", source_id=source_id)


def test_corrupt_pdf_is_unreadable(tmp_path: Path) -> None:
    path = tmp_path / "corrupt.pdf"
    path.write_bytes(b"%PDF-1.7\nnot a real pdf body\n")

    with pytest.raises(UnreadableDocumentError) as error:
        extract_document(path, source_id="upload:corrupt")

    assert isinstance(error.value.__cause__, PyPdfError)


def test_encrypted_pdf_is_unreadable(tmp_path: Path) -> None:
    """No password is accepted, so an encrypted file is simply unreadable."""
    path = tmp_path / "encrypted.pdf"
    writer = PdfWriter(clone_from=_TWO_PAGE_PDF)
    writer.encrypt("secret")
    writer.write(path)

    with pytest.raises(UnreadableDocumentError) as error:
        extract_document(path, source_id="upload:encrypted")

    assert isinstance(error.value.__cause__, PyPdfError)


def test_pdf_without_a_text_layer_is_unreadable(tmp_path: Path) -> None:
    """Stands in for a scanned, image-only PDF: readable file, no text, no OCR."""
    path = tmp_path / "blank.pdf"
    writer = PdfWriter()
    writer.add_blank_page(width=612, height=792)
    writer.write(path)

    with pytest.raises(UnreadableDocumentError, match="no extractable text"):
        extract_document(path, source_id="upload:blank")
