"""Named pack-local budgets for the test-design workflow."""

from __future__ import annotations

from collections.abc import Mapping

MAX_TICKET_IDENTIFIER_CHARS = 160
MAX_CANDIDATES = 40
MAX_SUGGESTED_CANDIDATES = 12
MAX_TITLE_CHARS = 200
MAX_RATIONALE_CHARS = 1_000
MAX_EVIDENCE_REFS = 16
MAX_EVIDENCE_TEXT_CHARS = 10_000
MAX_ID_CHARS = 128
MAX_AUTOMATION_RATIONALE_CHARS = 500
MAX_PRECONDITIONS_CHARS = 2_000
MAX_STEP_CHARS = 500
MAX_STEPS = 40
MAX_EXPECTED_RESULT_CHARS = 2_000
MAX_GHERKIN_CHARS = 8_000
MAX_EVIDENCE_FINGERPRINT_CHARS = 128
MAX_GENERATE_CANDIDATES = 20

PLAN_COVERAGE_MODEL_SETTINGS: Mapping[str, object] = {
    "temperature": 0,
    "max_tokens": 4096,
}

GENERATE_CASES_MODEL_SETTINGS: Mapping[str, object] = {
    "temperature": 0,
    "max_tokens": 8192,
}
